title: flatMap(Oslo) 2020
email: flatmap@arktekk.no
description: > # flatMap(Oslo) 2020 - functional programming conference
url: "https://2020.flatmap.no"

destination: _site
include: ["_pages"]
permalink: /:title/
exclude: [vendor]
includes:
  - _pages

collections:
  talks:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
